// 活动池 — 60条，每条预设五行标签
const ACTIVITIES = [
  // 动手
  { id: 1,  text: '做一顿没做过的菜',           tags: ['利火', '利土'], category: '动手' },
  { id: 2,  text: '收拾一个乱了一周的抽屉',      tags: ['利金', '利土'], category: '动手' },
  { id: 3,  text: '给植物浇水、擦叶子',           tags: ['利木', '利土'], category: '动手' },
  { id: 4,  text: '整理手机相册，删掉模糊的截图',  tags: ['利金'],         category: '动手' },
  { id: 5,  text: '把积灰的书翻出来读一章',        tags: ['利水', '利木'], category: '动手' },
  { id: 6,  text: '写几行字，什么内容都行',        tags: ['利水', '利木'], category: '动手' },
  { id: 7,  text: '修一样坏了很久的小东西',        tags: ['利金', '利火'], category: '动手' },
  { id: 8,  text: '跟着视频学一个简单的手工',      tags: ['利木', '利土'], category: '动手' },
  { id: 9,  text: '把冰箱里的食材拼成一顿饭',      tags: ['利火', '利土'], category: '动手' },
  { id: 10, text: '画点什么，不像也无所谓',         tags: ['利木', '利火'], category: '动手' },
  { id: 11, text: '重新摆放桌上物品的位置',         tags: ['利金', '利土'], category: '动手' },
  { id: 12, text: '手抄一首喜欢的诗',              tags: ['利水', '利木'], category: '动手' },
  // 出门
  { id: 13, text: '去附近公园散步二十分钟',        tags: ['利木', '利水'], category: '出门' },
  { id: 14, text: '逛一家没去过的店',              tags: ['利火', '利金'], category: '出门' },
  { id: 15, text: '骑共享单车随便绕三公里',        tags: ['利木', '利火'], category: '出门' },
  { id: 16, text: '去菜市场看今天有什么新鲜的',    tags: ['利火', '利土'], category: '出门' },
  { id: 17, text: '坐在公园长椅上看人',            tags: ['利水', '利木'], category: '出门' },
  { id: 18, text: '去河边或湖边待一会儿',          tags: ['利水'],         category: '出门' },
  { id: 19, text: '走路去一个步行可达但没去过的地方', tags: ['利木', '利土'], category: '出门' },
  { id: 20, text: '在楼下晒十分钟太阳',            tags: ['利火', '利木'], category: '出门' },
  { id: 21, text: '去书店翻翻书，不一定买',        tags: ['利水', '利木'], category: '出门' },
  { id: 22, text: '约个朋友出来喝杯东西',          tags: ['利火', '利金'], category: '出门' },
  { id: 23, text: '去天台或高处看看远处',          tags: ['利火', '利水'], category: '出门' },
  { id: 24, text: '傍晚出门看一会儿天',            tags: ['利水', '利火'], category: '出门' },
  // 静心
  { id: 25, text: '关掉手机安静坐一刻钟',          tags: ['利水', '利土'], category: '静心' },
  { id: 26, text: '泡一杯茶慢慢喝',                tags: ['利水', '利土'], category: '静心' },
  { id: 27, text: '听一张完整的专辑，不切歌',      tags: ['利水', '利金'], category: '静心' },
  { id: 28, text: '整理书架或CD架',               tags: ['利金', '利土'], category: '静心' },
  { id: 29, text: '拿笔随便写点什么，不给人看',    tags: ['利水', '利木'], category: '静心' },
  { id: 30, text: '看一部搁了很久的电影',          tags: ['利水', '利火'], category: '静心' },
  { id: 31, text: '把今天有意思的瞬间记下来',      tags: ['利水', '利木'], category: '静心' },
  { id: 32, text: '整理电脑桌面和文件夹',          tags: ['利金', '利土'], category: '静心' },
  { id: 33, text: '读一首诗，读出声',              tags: ['利水', '利木'], category: '静心' },
  { id: 34, text: '闭上眼睛听窗外的声音',          tags: ['利水'],         category: '静心' },
  { id: 35, text: '翻看旧照片或旧日记',            tags: ['利水', '利土'], category: '静心' },
  { id: 36, text: '做五分钟深呼吸',                tags: ['利水', '利木'], category: '静心' },
  // 社交
  { id: 37, text: '给一个很久没联系的朋友发条消息', tags: ['利火'],         category: '社交' },
  { id: 38, text: '在家人群里发张好玩的图',        tags: ['利火', '利木'], category: '社交' },
  { id: 39, text: '给外卖小哥认真说声谢谢',        tags: ['利土', '利火'], category: '社交' },
  { id: 40, text: '和楼下保安或邻居打个招呼',      tags: ['利土', '利火'], category: '社交' },
  { id: 41, text: '在评论区留一句认真的话',        tags: ['利火', '利金'], category: '社交' },
  { id: 42, text: '把一件小事讲给愿意听的人',      tags: ['利火', '利水'], category: '社交' },
  { id: 43, text: '约个饭，别光说改天',            tags: ['利火', '利土'], category: '社交' },
  { id: 44, text: '帮身边人做一件顺手的事',        tags: ['利土', '利金'], category: '社交' },
  { id: 45, text: '给爸妈打个电话',               tags: ['利火', '利土'], category: '社交' },
  { id: 46, text: '给朋友推荐一首最近喜欢的歌',    tags: ['利火', '利水'], category: '社交' },
  { id: 47, text: '在朋友圈发一条不用修图的动态',  tags: ['利火', '利木'], category: '社交' },
  { id: 48, text: '和一个陌生人在合适的地方聊两句', tags: ['利火', '利水'], category: '社交' },
  // 随便
  { id: 49, text: '把一件拖延小事现在就做了',      tags: ['利金', '利火'], category: '随便' },
  { id: 50, text: '戴着耳机出门随便走走',          tags: ['利水', '利木'], category: '随便' },
  { id: 51, text: '学一句有趣的方言',              tags: ['利木', '利火'], category: '随便' },
  { id: 52, text: '站在看得到天空的地方看一会儿',  tags: ['利水'],         category: '随便' },
  { id: 53, text: '把一件不再需要的东西送人或扔掉', tags: ['利金', '利土'], category: '随便' },
  { id: 54, text: '查一个一直好奇的问题',          tags: ['利水'],         category: '随便' },
  { id: 55, text: '用不同的路线走一段熟悉的路',    tags: ['利木', '利水'], category: '随便' },
  { id: 56, text: '找一首符合现在心情的歌',        tags: ['利水', '利火'], category: '随便' },
  { id: 57, text: '在阳台或窗边站一会儿',          tags: ['利水', '利木'], category: '随便' },
  { id: 58, text: '随机打开一本书读随机一页',      tags: ['利水', '利木'], category: '随便' },
  { id: 59, text: '写下明天的三个小目标',          tags: ['利金', '利木'], category: '随便' },
  { id: 60, text: '对着镜子对自己笑一下',          tags: ['利火'],         category: '随便' }
];
